name: test_workflow

on:
  push:
    branches: ["test"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ["self-hosted", "macOS", "ARM64"]

    steps:
      - name: Setup conda environment
        run: |
          conda init zsh 
          conda activate triton_example

      - name: Run a one-line script
        run: echo Hello, world!
