name: test_workflow

on:
  push:
    branches: ["test"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ["self-hosted", "macOS", "ARM64"]

    steps:
      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run python file in git repo
        run: |
          cd /Users/djyun/project/triton_server_example
          python3 temp.py
